---

- hosts: boaservers
  sudo: yes
  tasks:
  - name: create installs dir
    file: path=/opt/installs state=directory  
  - name: Download JDK
    get_url: url=https://www.dropbox.com/s/6cyvpjugczz6ze4/jdk-8u91-linux-x64.tar.gz?raw=1 dest=/opt/installs/jdk-8u91-linux-x64.tar.gz
  - name: create jdk install dir
    file: path=/opt/jdk state=directory
  - name: extract jdk
    unarchive: src=/opt/installs/jdk-8u91-linux-x64.tar.gz dest=/opt/jdk copy=no
    
  - name: Download Tomcat
    get_url: url=http://mirrors.sonic.net/apache/tomcat/tomcat-7/v7.0.70/bin/apache-tomcat-7.0.70.tar.gz dest=/opt/installs/apache-tomcat-7.0.70.tar.gz
  - name: create tomcat install dir
    file: path=/opt/tomcat state=directory    
  - name: extract tomcat
    unarchive: src=/opt/installs/apache-tomcat-7.0.70.tar.gz dest=/opt/tomcat copy=no

  - name: Download Active MQ
    get_url: url=http://archive.apache.org/dist/activemq/apache-activemq/5.9.0/apache-activemq-5.9.0-bin.tar.gz dest=/opt/installs/apache-activemq-5.9.0-bin.tar.gz
  - name: create activemq install dir
    file: path=/opt/activemq state=directory    
  - name: extract tomcat
    unarchive: src=/opt/installs/apache-activemq-5.9.0-bin.tar.gz dest=/opt/activemq copy=no
    
  - name: weblogic download
    get_url: url=https://dl.dropboxusercontent.com/u/69992010/prov/wls/orainventory.txt?raw=1 dest=/opt/installs/orainventory.txt
  - name: weblogic download2
    get_url: url=https://dl.dropboxusercontent.com/u/69992010/prov/wls/wlsresponsefile.txt?raw=1 dest=/opt/installs/wlsresponsefile.txt
  - name: weblogic download 3
    get_url: url=https://www.dropbox.com/s/p1sxfszysisudl6/wlsinstall.sh?raw=1 dest=/opt/installs/wlsinstall1.sh mode=0777    
  - name: weblogic download 4
    get_url: url=https://dl.dropboxusercontent.com/u/69992010/prov/fmw_12.1.3.0.0_wls.jar?raw=1 dest=/opt/installs/fmw_12.1.3.0.0_wls.jar

